# Specify docker image
image: debian:stretch

stages:
  - tarballs

build-release:
  stage: tarballs
  only:
    - master
  script:
    - release="$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')"
    - mkdir ../argonaut-$release/
    - mv ./* ../argonaut-$release/
    - mv  ../argonaut-$release/ ./
    - tar -cvzf argonaut-$release.tar.gz *
  artifacts:
    paths:
    - argonaut-*.tar.gz
