# Specify docker image
image: debian:stretch

# Define variable to disable SSL verification of GIT
variables:
  GIT_SSL_NO_VERIFY: "true"

# Execute before every job
# Install libperl-critic-perl
before_script:
  - apt-get update -qq
  - apt-get install -y -qq libperl-critic-perl

# Generate perlcritic rapport
create_perlcritic_rapport:
  except:
    - branches
    - tags
  script:
    - perlcritic --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" .
