# Define variable
variables:
  CI_REPOSITORY_URL: "http://gitlab.fusiondirectory.org/jswaelens/argonaut.git"

# Execute before every job
# Install libperl-critic-perl and ca-certificates
before_script:
  - apt-get update -qq
  - apt-get install -y -qq libperl-critic-perl ca-certificates

# Generate perlcritic rapport
create_perlcritic_rapport:
  script:
    - export
    - perlcritic --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" . > perlcritic_report.txt
