stages:
  - lint
  - codestyle
  - tarballs
  - trigger

# Perl lint
create_perl_lint_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd/perlcodestyle-cli:buster
  stage: lint
  only:
    - branches
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq libapp-daemon-perl libconfig-inifiles-perl libdigest-sha-perl libfile-pid-perl libio-socket-ssl-perl
    - apt-get install -y -qq libjson-perl libjson-rpc-perl liblog-handler-perl libmodule-pluggable-perl libnet-ldap-perl libpath-class-perl libxml-sax-expatxs-perl
    - apt-get install -y -qq bind9utils libdns-zoneparse-perl
    - apt-get install -y -qq libquota-perl
    - apt-get install -y -qq libdatetime-perl libpoe-perl libpoe-component-pool-thread-perl libpoe-component-schedule-perl libpoe-component-server-jsonrpc-perl libpoe-component-server-simplehttp-perl libpoe-component-sslify-perl
    - apt-get install -y -qq libhttp-daemon-ssl-perl
    - apt-get install -y -qq fuse libfuse-perl
    - apt-get install -y -qq debmirror libwww-perl
    - apt-get install -y -qq libmail-sendmail-perl
    - apt-get install -y -qq libfile-slurp-perl libdigest-perl-md5-perl
    - apt-get install -y -qq librest-client-perl
  script:
    - find . -type f -name '*.pm' -print0 | xargs -0 -n1 perl -cw -I argonaut-ldap2zone -I argonaut-common

# generate man pages to test validity
create_manpages_lint_report:
  image: registry.fusiondirectory.org/fusiondirectory/fd/perlcodestyle-cli:buster
  stage: lint
  only:
    - branches
  script:
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-client/bin/argonaut-client argonaut-client/man/argonaut-client.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-common/man/argonaut.conf.pod argonaut-common/man/argonaut.conf.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fai-mirror/bin/argonaut-debconf-crawler  argonaut-fai-mirror/man/argonaut-debconf-crawler.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fai-mirror/bin/argonaut-repository argonaut-fai-mirror/man/argonaut-repository.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fai-monitor/bin/argonaut-fai-monitor argonaut-fai-monitor/man/argonaut-fai-monitor.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fai-nfsroot/bin/argonaut-ldap2fai  argonaut-fai-nfsroot/man/argonaut-ldap2fai.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fai-server/bin/fai2ldif argonaut-fai-server/man/fai2ldif.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fai-server/bin/yumgroup2yumi argonaut-fai-server/man/yumgroup2yumi.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fuse/bin/argonaut-fuse  argonaut-fuse/man/argonaut-fuse.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fusiondirectory/bin/argonaut-clean-audit argonaut-fusiondirectory/man/argonaut-clean-audit.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-fusiondirectory/bin/argonaut-user-reminder argonaut-fusiondirectory/man/argonaut-user-reminder.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-ldap2zone/bin/argonaut-ldap2zone  argonaut-ldap2zone/man/argonaut-ldap2zone.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-quota/bin/argonaut-quota argonaut-quota/man/argonaut-quota.1
    - pod2man -c "Argonaut Documentation" -r "Argonaut 1.3" argonaut-server/bin/argonaut-server argonaut-server/man/argonaut-server.1
    - lexgrog argonaut-client/man/argonaut-client.1
    - lexgrog argonaut-common/man/argonaut.conf.1
    - lexgrog argonaut-fai-mirror/man/argonaut-debconf-crawler.1
    - lexgrog argonaut-fai-mirror/man/argonaut-repository.1
    - lexgrog argonaut-fai-monitor/man/argonaut-fai-monitor.1
    - lexgrog argonaut-fai-nfsroot/man/argonaut-ldap2fai.1
    - lexgrog argonaut-fai-server/man/fai2ldif.1
    - lexgrog argonaut-fai-server/man/yumgroup2yumi.1
    - lexgrog argonaut-fuse/man/argonaut-fuse.1
    - lexgrog argonaut-fusiondirectory/man/argonaut-clean-audit.1
    - lexgrog argonaut-fusiondirectory/man/argonaut-user-reminder.1
    - lexgrog argonaut-ldap2zone/man/argonaut-ldap2zone.1
    - lexgrog argonaut-quota/man/argonaut-quota.1
    - lexgrog argonaut-server/man/argonaut-server.1


# Generate perlcritic rapport
create_perlcritic_rapport:
  image: registry.fusiondirectory.org/fusiondirectory/fd/perlcodestyle-cli:buster 
  stage: codestyle
  only:
    - branches
    - tags
  script: 
    - perlcritic .

build-tarballs:
  stage: tarballs
  script:
    - mkdir ../argonaut-1.4/
    - mv ./* ../argonaut-1.4/
    - mv  ../argonaut-1.4/ ./
    - tar -cvzf argonaut-1.4.tar.gz *
  artifacts:
    paths:
    - argonaut-1.4.tar.gz
    expire_in: 30d

build-release:
  stage: tarballs
  only:
    - tags
  script:
    - tar -cvzf argonaut-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"').tar.gz *
  artifacts:
    paths:
      - argonaut-$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"').tar.gz


trigger-ci-debian-buster:
  stage: trigger
  only:
    - branches
  variables:
    GROUP: "$GROUP"
    BRANCH: "$CI_COMMIT_REF_NAME"
  trigger:
    project: debian/buster-argonaut-dev
    branch: "$BRANCH_BUILD_DEBIAN_BUSTER"

trigger-ci-centos-7:
  stage: trigger
  only:
    - branches
  variables:
    GROUP: "$GROUP"
    BRANCH: "$CI_COMMIT_REF_NAME"
  trigger:
    project: centos/centos7-argonaut-dev
    branch: "$BRANCH_BUILD_CENTOS_7"
