# Specify docker image
image: debian:stretch

stages:
  - tarballs
  - trigger

build-release:
  stage: tarballs
  only:
    - master
  script:
    - release="$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')"
    - mkdir ../argonaut-$release/
    - mv ./* ../argonaut-$release/
    - mv  ../argonaut-$release/ ./
    - tar -cvzf argonaut-$release.tar.gz *
  artifacts:
    paths:
    - argonaut-*.tar.gz

trigger-ci-debian-stretch:
  stage: trigger
  only:
    - master
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_DEBIAN_STRETCH: "$BRANCH_BUILD_DEBIAN_STRETCH"
  trigger:
    project: debian/stretch-argonaut-release
    branch: "$BRANCH_BUILD_DEBIAN_STRETCH"

trigger-ci-debian-buster:
  stage: trigger
  only:
    - master
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_DEBIAN_BUSTER: "$BRANCH_BUILD_DEBIAN_BUSTER"
  trigger:
    project: debian/buster-argonaut-release
    branch: "$BRANCH_BUILD_DEBIAN_BUSTER"

trigger-ci-centos7:
  stage: trigger
  only:
    - master
  variables:
    GROUP: "$GROUP"
    BRANCH_CORE: "$CI_COMMIT_REF_NAME"
    BRANCH_PLUGIN: "$CI_COMMIT_REF_NAME"
    BRANCH_BUILD_CENTOS_7: "$BRANCH_BUILD_CENTOS_7"
  trigger:
    project: centos/centos7-argonaut-release
    branch: "$BRANCH_BUILD_CENTOS_7"
