# Execute before every job
# Install libperl-critic-perl and authorize git clone without ssl verification
before_script:
  - apt-get update -qq
  - apt-get install -y -qq libperl-critic-perl

# Configure git to autorized no ssl verification
configure_git:
  script:
    - git config --global http.sslVerify false

# Generate perlcritic rapport
create_perlcritic_rapport:
  script:
    - perlcritic --quiet --verbose "%f~|~%s~|~%l~|~%c~|~%m~|~%e~|~%p~||~%n" . > perlcritic_report.txt
