#######################################################################
#
# Argonaut::Fuse::Common
#
# Copyright (c) 2005,2006,2007 by Jan-Marek Glogowski <glogow@fbihome.de>
# Copyright (c) 2008 by Cajus Pollmeier <pollmeier@gonicus.de>
# Copyright (c) 2008,2009, 2010 by Jan Wenzel <wenzel@gonicus.de>
# Copyright (C) 2011 FusionDirectory project <contact@fusiondirectory.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#
#######################################################################

package Argonaut::Fuse::Common;

sub write_pxe_config_file {

  my ($host,$file,$kernel,$append, $filesystem) = @_;

  # Get IP address
  my $ip_bytes = inet_aton( $host ) if($host);
  my $ipaddr = (defined $ip_bytes) ? inet_ntoa( $ip_bytes ) : 'unknown';
  if(not $host or "" eq $host) {
    $host = $ipaddr;
  }

  my $file_content= "#generated by argonaut-fuse for host $host with IP $ipaddr\n";
  $file_content.= "default argonaut-fuse-generated\n\n";
  $file_content.= "label argonaut-fuse-generated\n";
  $file_content.= "$kernel\n";
  if($append) {
    $file_content.= "append $append\n";
  }

  # store in hash
  $filesystem->{'root'}->{'content'}->{$file}->{'type'}= 'file';
  $filesystem->{'root'}->{'content'}->{$file}->{'content'}= $file_content;

  return 0;
}

1;

__END__

# vim:ts=2:sw=2:expandtab:shiftwidth=2:syntax:paste
