#!/bin/bash
# (c) 2011-2014 The FusionDirectory Project <contact@fusiondirectory.org>

### BEGIN SUBROUTINE INFO
# Provides-Var:
# Requires-Var:  $FAI $LOGDIR
# Suggests-Var:
# Short-Description: get $FAI from an ldap server.
### END SUBROUTINE INFO

# Create configuration space
MAC=`argonaut-getid $IPADDR`
ldap2fai -v -c $FAI -n $HOSTNAME -m $MAC | tee /tmp/fai/ldap2fai.log

