#!/bin/sh 

# Read what LDAP and GOsa-SI provide
[ -f /etc/sysconfig/argonaut ] && . /etc/sysconfig/argonaut
#[ -f /var/run/gosa-si-client.opts ] && . /var/run/gosa-si-client.opts

# Unify MAC address
MAC=$(echo $MAC | tr 'a-f' 'A-F')

# Set $SERVER depending on the method
case "$XMETHOD" in
        ldm) SERVER="SERVER"
             ;;
        shell)
             ;;
        telnet) SERVER="TELNET_HOST"
             ;;
        xdmcp) SERVER="XDM_SERVER"
             ;;
        rdp) SERVER="RDP_SERVER"
	     XMETHOD="rdesktop"
             ;;
        *)   SERVER="SERVER"
             ;;
esac

# Create the MAC part of the lts.conf
cat <<EOF >> /etc/lts.conf

[$MAC]
    SCREEN_07=$XMETHOD
    $SERVER=$XDMCPSERVER
    CONSOLE_KEYMAP=$XKBLAYOUT
    NETWORK_COMPRESSION=True
    CONFIGURE_X=False
EOF

# Set the RDP default color depth
if [ "$XMETHOD" == "rdesktop" ]; then
	cat <<-EOF >> /etc/lts.conf
	  RDP_OPTIONS="-a $XCOLORDEPTH"
	EOF
fi

# Configure swap server
if [ "$SWAPSERVER" != "!" ]; then
	cat <<-EOF >> /etc/lts.conf
	    USE_LOCAL_SWAP=False
	    NBD_SWAP=true
	    SWAP_SERVER=$(echo -n $SWAPSERVER | cut -d: -f2)
	    NBD_PORT=$(echo -n $SWAPSERVER | cut -d: -f3)
	EOF
else
	cat <<-EOF >> /etc/lts.conf
	    USE_LOCAL_SWAP=True
	    NBD_SWAP=False
	EOF
fi

# Enable sane service
if [ "$SCANNERENABLE" == "1" ]; then
	echo "sane-port stream tcp nowait saned.saned /usr/sbin/saned saned" >> /etc/inetd.conf
fi

# Configure printer service
if [ -n "$LPDENABLE" ]; then
	
	for device in $(sed -n 's/^LPDENABLE="\(.*\)"$/\1/p' /etc/sysconfig/argonaut | sort -n); do

	  n=2
	  number=$(echo $device | cut -d: -f1)
	  type=$(echo $device | cut -d: -f2)
	  echo "    PRINTER_${number}_TYPE=$type" >> /etc/lts.conf
	  for var in DEVICE PORT SPEED FLOWCONTROL PARITY DATABITS WRITE_ONLY OPTIONS; do
	    (( n++ ))
	    value=$(echo $device | cut -d: -f$n)
	    [ "$value" != "" ] && echo "    PRINTER_${number}_$var=$value" >> /etc/lts.conf
	  done

	done

	. /usr/share/ltsp/ltsp-init-common
	configure_printer

fi

