#!/bin/sh

# Source configuration file
[ -f /etc/sysconfig/argonaut ] && . /etc/sysconfig/argonaut

# Write ntpdate defaults if NTPSERVER has been provided
if [ -n "$NTPSERVER" ]; then
	echo "NTPSERVERS=\"$NTPSERVER\"" > /etc/default/ntp-servers
	
	echo "NTPSERVERS=\"$NTPSERVER\"" > /etc/default/ntpdate

	ntpdate-debian &> /dev/null
	hwclock --systohc 2>&1 >/dev/null
fi
