#!/bin/bash
# This script is looking for disabled printers and enabled them.
# Created by Jens Nitschke
for printer in `/usr/bin/lpstat -p |/bin/grep 'disabled' |/usr/bin/awk '{print $2}'`;
do
  /usr/bin/enable $printer
done

for printer in `/usr/bin/lpstat -a |/bin/grep 'not accepting' |/usr/bin/awk '{print $1}'`;
do
  /usr/sbin/accept $printer
done  
