#!/bin/sh

[ -z "$SUDO_USER" ] && exit 0

# Don't do this if there's no gosa-si-client running
pgrep gosa-si-client &> /dev/null || exit 0

if ps uxw -u $SUDO_USER | grep -q argonaut-end-session; then
        echo LOGOUT $SUDO_USER > /var/run/gosa-si-client.socket
else
        echo LOGIN $SUDO_USER > /var/run/gosa-si-client.socket
fi
