#!/bin/sh

IPOS=$HOME/.kde/share/apps/kdesktop/IconPositions
mkdir -p $(dirname $IPOS)

if [ ! -s $IPOS ]; then

	Y=16

	for link in $HOME/Desktop/*; do

		link=$(basename $link)
		[ "$link" == "trash.desktop" ] && continue
		
		cat <<-EOF
		[IconPosition::$link]
		Xabs=34
		Yabs=$Y
		
		EOF
	
		Y=$(( $Y + 100 ))
	
	done > $IPOS

	# Calculate Trash positions
	res=$(xdpyinfo | awk '/dimensions:/ {print $2}')
	res_x=${res%x*}
	res_y=${res#*x}

	cat >> $IPOS <<-EOF
	[IconPosition::trash.desktop]
	Xabs=$(( res_x - 107 ))
	Yabs=$(( res_y - 83 ))
	EOF
fi

