#!/bin/sh
# Copyright (C) 2005  Holger Burbach <holger.burbach@gonicus.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

##########################################################################

. /usr/lib/argonaut/argonaut-support.lib
. /etc/argonaut/argonaut-agent.conf

##########################################################################

DEBUG=YES
BLACKLISTFILE="/etc/argonaut/profile-exclude.list"

##########################################################################

dprint "Profil-Download started..."

HOME=$(ldap_get_home_of $SUDO_USER)
HOMEDIR=`basename $HOME`

if [ -n $HOME ]; then
	l_profile="$HOME"
	p_profile="/mnt/profiles/$SUDO_USER"
	
	#
	# Profile is mounted drive?
	#
	grep -q "$p_profile" /etc/mtab
	if [ $? -eq 1 ]; then
		dprint "ERROR: Profile-drive is not mounted. Profile-Download aborted!"
	else		
		if [ -e $p_profile/profile/$HOMEDIR/1.0/profil-$SUDO_USER.db ]; then
			NEWSYNC=1

			ltimestampFile="$l_profile/.profileTimestamp"
			ptimestampFile="$p_profile/profile/$HOMEDIR/1.0/.profileTimestamp"
		else
			NEWSYNC=0

			ltimestampFile="$l_profile/.profileTimestamp"
			ptimestampFile="$p_profile/$HOMEDIR/.profileTimestamp"
		fi

		if [ -s $ltimestampFile ]; then
			ltimestamp=`head -1 $ltimestampFile | grep "20[0-9]*"`
		else
			ltimestamp=""
		fi
		
		if [ -s $ptimestampFile ]; then
			ptimestamp=`head -1 $ptimestampFile | grep "20[0-9]*"`
		else
			ptimestamp=""
		fi
		
		if [ -z "$ptimestamp" ]; then
			dprint "Time stamp of the profile to profile server invalid. Abort!"
		else	
			dprint "ptimestamp=$ptimestamp"
			dprint "ltimestamp=$ltimestamp"
			
			if [ -z "$ltimestamp" ] || [ $ptimestamp -gt $ltimestamp ]; then
				dprint "Syncing"
				#
                		# ACHTUNG: Unbeding rsync >= 2.6.8 benutzen!!!
                		#
				if [ $NEWSYNC -eq 1 ]; then
					/usr/sbin/argonaut-profile-sync -v -s $l_profile -d $p_profile/profile/$HOMEDIR/1.0 -e $BLACKLISTFILE restore 
					result_download=$?

					if [ ! $result_download -eq 0 ]; then
						Xdialog --msgbox "The download of your profile from the profile server has failed!" 12 70
						umount $p_profile
						rm -f "$HOME/.profileTimestamp"
						exit 1
					fi
				else
                                	#
                                	# Attention use rsync >= 2.6.8 !!!
                                	#
                                	rsync -rpvx --modify-window=5 --delete --force --exclude-from=$BLACKLISTFILE $p_profile/$HOMEDIR /home/
					result_download=$?
					
					tar -xzC / -f $p_profile/$HOMEDIR/.symlinks.tar.gz
					rm -f $HOME/.symlinks.tar.gz

					if [ ! $result_download -eq 0 ]; then
						Xdialog --msgbox "The download of your profile from the profile server has failed!" 12 70
						umount $p_profile
						rm -f "$HOME/.profileTimestamp"
						exit 1
					fi
				fi
			else
				dprint "Local profil is up-to-date. Nothing to do!"
			fi
		fi
		
		dprint "Customizing the permissions in your home directory ..."
		if [ $NEWSYNC -eq 0 ]; then
			find $HOME -xdev \( -user root -o -group root \) -print -exec chown ${SUDO_UID}.${SUDO_GID} {} \;
		fi
	fi
else
	# kein Home -> kein LDAP -> ENDE
	dprint "No Home -> no LDAP? -> END"
fi

#
# Update local time stamp
#
timestampFile="$HOME/.profileTimestamp"
timestamp=`date "+%Y%m%d%H%M%S"`
echo "$timestamp" > $timestampFile

dprint "Profil-Download terminated."
