
=head1 NAME

fts.conf - Configuration file for fts a FUSE/TFTP supplicant targeted to work with LDAP entries written by GOsa


=head1 DESCRIPTION

The fts.conf file defines all parameter fts needs for running. It is normally located in the /etc/fts/ directory and is generated automatically by the fts(1) program during installation. 

=head1 DIRECTIVES


=head2 [General]

=over 4

=item dflt_init = install

Defines the default fts initialisation mode.

=item logfile = /var/log/fts.log

Define the location of the logfile.

=item pid-file = /var/run/fts.pid

Defines the location for the pid file.

=item loglevel=5

Define the default loglevel

=back


=head2 [TFTP]

=over 2

=item pxelinux_cfg = /srv/fai/boot/pxelinux.cfg

Define the location for the tftp root

=item pxelinux_cfg_static = /srv/fai/boot/pxelinux.static

Define the location for directory containing files that should be present in "pxelinux.cfg" when mounted (i.e. /srv/fai/boot/pxelinux.static/default will be accessible as /srv/fai/boot/pxelinux.cfg/default)

=back


=head2 [LDAP]

=over 6

=item auth_dn =

Define the bind dn for the connection to the ldap server

=item auth_pwd =

Define the bind password for the connection to the ldap server

=item config = /etc/ldap/ldap.conf

Define where the ldap config is stored

=item fork_idle = 300

=item fork_max = 10

=item fork_min = 2

=back


=head2  [FAI]

=over 4

=item fai_flags = verbose,syslogd,reboot vga=0

Define the fai flags used by fts

=item nfs_opts =

Define the nfs options that can be passed to fts for fai

=item nfs_root = /srv/fai/nfsroot

Define the nfsroot for fai

=item union = aufs

Define the type of filesystem used in fai live system

=back


=head2  [OPSI]

=over 4

=item admin = 

Define the admin user for the opsi server

=item password = 

Define the admin password for the opsi server

=item server = 

Define the ip of fqdn address of the opsi server

=item lang = de

Define the default language for the opsi installer

=back

=head1 BUGS

Please report any bugs, or post any suggestions, to the fusiondirectory mailing list fusiondirectory-users or to
<https://forge.fusiondirectory.org/projects/goto2/issues/new>

=head1 LICENCE AND COPYRIGHT

This code is part of FusionDirectory <http://www.fusiondirectory.org>

=over 2

=item Copyright (C) 2010 by Jan Wenzel <wenzel@gonicus.de>

=item Copyright (C) 2011 FusionDirectory project

=back

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

=cut
